# Generated by Django 2.1.2 on 2018-11-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rescatados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('tamanio', models.CharField(max_length=10)),
                ('peso', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=80)),
                ('fechaRescate', models.DateField()),
                ('Estado', models.CharField(choices=[('R', 'Rescatado'), ('D', 'Disponible'), ('A', 'Adoptado')], default='D', max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
