# Generated by Django 2.1.2 on 2018-11-10 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rescatados', '0002_auto_20181110_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perro',
            old_name='tamanio',
            new_name='tamaño',
        ),
    ]
